apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mg4istsiq-python
  janus-idp.io/tekton: mg4istsiq-python
  backstage.io/kubernetes-id: mg4istsiq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mg4istsiq-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
