apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mg4istsiq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mg4istsiq-python 
  name: mg4istsiq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mg4istsiq-python 
